version: '3'

services:

  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - ./migration/up:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lab3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    container_name: app
    build: ./

    depends_on:
      - db
#        condition: service_healthy
    ports:
      - "8080:8080"


volumes:
  postgres_data: